server:
  port: 1234
spring:
  datasource:
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
    metadata:
      url: "jdbc:mysql://localhost:3306/qhive"
      username: "qhive"
      password: "qhive@123@"
  jpa:
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
hive:
  datasource:
      url: "jdbc:hive2://ip-172-31-0-55.ap-southeast-1.compute.internal:2181,ip-172-31-10-50.ap-southeast-1.compute.internal:2181,ip-172-31-10-79.ap-southeast-1.compute.internal:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2"
      username: "hive"
      password: ""
      driver-class-name: "org.apache.hive.jdbc.HiveDriver"